name: Auto Ping Websites

on:
  schedule:
    - cron: '0 0 */3 * *' # 3 நாட்களுக்கு ஒருமுறை
  workflow_dispatch: # மேனுவலாக இயக்க

jobs:
  ping_job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URLs 20 times
        run: |
          echo "Starting the ping process..."
          for i in {1..20}
          do
            echo "Ping attempt: $i"
            
            # Ping first URL
            curl -s -o /dev/null -L -w "URL 1 HTTP Status: %{http_code}\n" https://2009shiny.gamer.gd/
            
            # Ping second URL
            curl -s -o /dev/null -L -w "URL 2 HTTP Status: %{http_code}\n" "https://23122009shiny.gt.tc/?i=1"
            
            if [ $i -lt 20 ]; then
              echo "Waiting 90 seconds before next ping..."
              sleep 90
            fi
          done
          echo "All 20 pings completed."
          
